/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:88759bf5-a586-4318-bdc6-bc682f760d71",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_fQ8kVTTuu",
    "aws_user_pools_web_client_id": "175055tip6aagjcpoak34efo95",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://uf4tseiy5rg35e6b2tk6a5b7bm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-s5thv4x4hbemnb6mooqbypgziu"
};


export default awsmobile;
