//export const Endpoint = "http://localhost:9080"
//export const Endpoint = "https://cell-group-accounting.herokuapp.com:9080"
//export const Endpoint = "https://main.dslriwa6h76ii.amplifyapp.com:9080"
export const Endpoint = ""
//export const Endpoint = "https://api.github.com:9080"